# Generated by Django 5.2.17 on 2026-08-18 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaffoftir_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_identified', models.PositiveIntegerField(default=0)),
                ('total_unknown', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
                ('range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaffoftir_api.shootingrange')),
            ],
            options={
                'db_table': 'face_check_ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceCheckInEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField(help_text='Order in queue')),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('UNKNOWN', 'Unknown'), ('MANUAL', 'Manual Override')], default='IDENTIFIED', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Face match confidence 0-1')),
                ('photo_captured', models.URLField(blank=True, help_text='Captured photo during check-in')),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shaffoftir_api.facecheckin')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaffoftir_api.employee')),
            ],
            options={
                'db_table': 'face_check_in_entries',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='FaceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('face_encoding', models.TextField(help_text='Base64-encoded face embedding vector')),
                ('photo_reference', models.URLField(blank=True, help_text='Reference photo URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_registrations', to='shaffoftir_api.employee')),
            ],
            options={
                'db_table': 'face_registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_rank', models.CharField(blank=True, max_length=100)),
                ('employee_department', models.CharField(blank=True, max_length=255)),
                ('sequence_number', models.PositiveIntegerField(help_text='Position in queue (1-based)')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CURRENT', 'Current Shooter'), ('SHOOTING', 'Shooting'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=20)),
                ('pre_shoot_photo', models.URLField(blank=True, help_text='Target photo before shooting')),
                ('post_shoot_photo', models.URLField(blank=True, help_text='Target photo after shooting')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_shots', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('miss_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaffoftir_api.employee')),
            ],
            options={
                'db_table': 'queue_entries',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='ShootingQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('total_soldiers', models.PositiveIntegerField(default=0)),
                ('current_position', models.PositiveIntegerField(default=0, help_text='Index of current shooter (0-based)')),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('auto_advance', models.BooleanField(default=True, help_text='Auto-advance to next soldier on completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='shaffoftir_api.facecheckin')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_queues', to=settings.AUTH_USER_MODEL)),
                ('lane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaffoftir_api.shootinglane')),
                ('range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shaffoftir_api.shootingrange')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='shaffoftir_api.shootingsession')),
            ],
            options={
                'db_table': 'shooting_queues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShotAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('soldier_seq', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('before_photo_url', models.URLField(blank=True, help_text='Target photo before shooting')),
                ('after_photo_url', models.URLField(blank=True, help_text='Target photo after shooting')),
                ('annotated_photo_url', models.URLField(blank=True, help_text='AI-annotated photo with hit markers')),
                ('detected_hits', models.JSONField(default=list, help_text='List of detected hit positions: [{"x": 0.5, "y": 0.3, "score": 10}, ...]')),
                ('detected_misses', models.JSONField(default=list, help_text='List of detected miss positions')),
                ('total_shots_detected', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('miss_count', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0, help_text='AI confidence in analysis 0-1')),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shot_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OperatorComment',
        ),
        migrations.DeleteModel(
            name='ReviewReason',
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shaffoftir_api.shootingqueue'),
        ),
        migrations.AddField(
            model_name='shotanalysis',
            name='queue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='shaffoftir_api.queueentry'),
        ),
        migrations.AddField(
            model_name='shotanalysis',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='shaffoftir_api.shootingsession'),
        ),
        migrations.AddIndex(
            model_name='facecheckin',
            index=models.Index(fields=['status', 'created_at'], name='face_check__status_ab2b48_idx'),
        ),
        migrations.AddIndex(
            model_name='facecheckinentry',
            index=models.Index(fields=['check_in', 'sequence_number'], name='face_check__check_i_d06d71_idx'),
        ),
        migrations.AddIndex(
            model_name='facecheckinentry',
            index=models.Index(fields=['check_in', 'status'], name='face_check__check_i_feb53a_idx'),
        ),
        migrations.AddIndex(
            model_name='faceregistration',
            index=models.Index(fields=['employee', 'is_active'], name='face_regist_employe_e4d263_idx'),
        ),
        migrations.AddIndex(
            model_name='shootingqueue',
            index=models.Index(fields=['status'], name='shooting_qu_status_6549b6_idx'),
        ),
        migrations.AddIndex(
            model_name='shootingqueue',
            index=models.Index(fields=['instructor', 'status'], name='shooting_qu_instruc_823297_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['queue', 'sequence_number'], name='queue_entri_queue_i_ebc1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['queue', 'status'], name='queue_entri_queue_i_e54ded_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('queue', 'sequence_number'), name='unique_queue_sequence'),
        ),
        migrations.AddIndex(
            model_name='shotanalysis',
            index=models.Index(fields=['status'], name='shot_analys_status_d1996c_idx'),
        ),
        migrations.AddIndex(
            model_name='shotanalysis',
            index=models.Index(fields=['session', 'soldier_seq'], name='shot_analys_session_44c2ba_idx'),
        ),
    ]
