# Generated by Django 5.2.17 on 2026-08-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaffoftir_api', '0002_facecheckin_facecheckinentry_faceregistration_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shootinglane',
            name='unique_lane_number_per_range',
        ),
        migrations.AddField(
            model_name='rangerubeg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rangerubeg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rangerubeg',
            name='max_lanes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='shootinglane',
            name='rubeg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='shaffoftir_api.rangerubeg'),
        ),
        migrations.AddField(
            model_name='shootingsession',
            name='rubeg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shootingsession',
            name='rubeg_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rangerubeg',
            name='distance',
            field=models.IntegerField(default=25),
        ),
        migrations.AddConstraint(
            model_name='rangerubeg',
            constraint=models.UniqueConstraint(fields=('range', 'rubeg_number'), name='unique_rubeg_number_per_range'),
        ),
        migrations.AddConstraint(
            model_name='shootinglane',
            constraint=models.UniqueConstraint(condition=models.Q(('rubeg__isnull', True)), fields=('range', 'lane_number'), name='unique_lane_number_per_range'),
        ),
        migrations.AddConstraint(
            model_name='shootinglane',
            constraint=models.UniqueConstraint(condition=models.Q(('rubeg__isnull', False)), fields=('rubeg', 'lane_number'), name='unique_lane_number_per_rubeg'),
        ),
    ]
